module.exports = {
  ACTION: Object.freeze({
    // USER
    USER_GET: "HTTP://LOCALHOST:9000/API/USERS/LOGIN",

    // MVO
    CSR_GET_ALL: "HTTP://LOCALHOST:9000/API/CSRS/",
    CSR_GET_ID: "FETCHING A SPECIFIC MVO",
    CSR_GET_ALL_FOR_CATEGORY: "HTTP://LOCALHOST:9000/API/CATEGORIES/{0}/CSRS",

    // DATASOURCES
    // SDG_GET_ALL: "HTTP://LOCALHOST:9000/API/SDGS/",
    SDG_GET_ALL_FOR_CATEGORY: "HTTP://LOCALHOST:9000/API/SDGS/CATEGORY/",
    SDG_GET_ID: "FETCHING A SPECIFIC SDG",

    // DATASOURCES
    DATASOURCE_GET_ALL: "FETCHING ALL DATASOURCES",
    DATASOURCE_GET_ID: "FETCHING A SPECIFIC DATASOURCE",

    // DATASOURCE MELDINGEN
    DATASOURCE_MELDINGEN_GET_ALL: "FETCHING ALL DATASORUCE MELDINGEN",
    DATASOURCE_MELDINGEN_GET_ID: "FETCHING A SPECIFIC DATASOURCE MELDING",

    //CATEGORIEENA
    CATEGORIEEN_GET_ALL: "HTTP://LOCALHOST:9000/API/CATEGORIES/",
    CATEGORIEEN_GET_ID: "FETCHING A SPECIFIC CATEGORIE",
  }),
};
